name:                type-classes-and-list-functions
version:             0.1.0.0
github:              "shepherdjerred-homework/type-classes-and-list-functions"
license:             GPL
author:              "Jerred Shepherd"
maintainer:          "shepherdjerred@gmail.com"
copyright:           "Jerred Shepherd"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shepherdjerred/type-classes-and-list-functions#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  type-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - type-classes-and-list-functions
      - hspec
